// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2s8LugQbHlhAgbhIi_VBynGLYg5edJYE',
    appId: '1:152363072866:web:ad86b03ad6023db06a003b',
    messagingSenderId: '152363072866',
    projectId: 'mazi-mess-501105',
    authDomain: 'mazi-mess-501105.firebaseapp.com',
    storageBucket: 'mazi-mess-501105.firebasestorage.app',
    measurementId: 'G-SJZKRLP5W0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRaZxiGyjY_m1IqxtQYIe5ZmwUMWdWgz0',
    appId: '1:152363072866:android:f4adbce775938ef06a003b',
    messagingSenderId: '152363072866',
    projectId: 'mazi-mess-501105',
    storageBucket: 'mazi-mess-501105.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6rUP6uFjKxXUQIBPUaXCiQQPREi8a43M',
    appId: '1:152363072866:ios:6e0770b3cc78417a6a003b',
    messagingSenderId: '152363072866',
    projectId: 'mazi-mess-501105',
    storageBucket: 'mazi-mess-501105.firebasestorage.app',
    iosBundleId: 'com.example.maziMess',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6rUP6uFjKxXUQIBPUaXCiQQPREi8a43M',
    appId: '1:152363072866:ios:6e0770b3cc78417a6a003b',
    messagingSenderId: '152363072866',
    projectId: 'mazi-mess-501105',
    storageBucket: 'mazi-mess-501105.firebasestorage.app',
    iosBundleId: 'com.example.maziMess',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2s8LugQbHlhAgbhIi_VBynGLYg5edJYE',
    appId: '1:152363072866:web:18330273e0b8a9cf6a003b',
    messagingSenderId: '152363072866',
    projectId: 'mazi-mess-501105',
    authDomain: 'mazi-mess-501105.firebaseapp.com',
    storageBucket: 'mazi-mess-501105.firebasestorage.app',
    measurementId: 'G-BE6XSLSEFE',
  );
}
