import '../../models/plan_model.dart';

final fakePlans = <Plan>[
  const Plan(
    planId: 'plan_001',
    messId: 'mess_001',
    planName: 'Lunch Only',
    description: 'Daily lunch thali with roti, rice, dal, and sabzi.',
    price: 2500,
    durationDays: 30,
    mealTypes: ['Lunch'],
    isActive: true,
  ),
  const Plan(
    planId: 'plan_002',
    messId: 'mess_001',
    planName: 'Full Day',
    description: 'Breakfast, lunch, and dinner with weekly special menu.',
    price: 4500,
    durationDays: 30,
    mealTypes: ['Breakfast', 'Lunch', 'Dinner'],
    isActive: true,
  ),
  const Plan(
    planId: 'plan_003',
    messId: 'mess_001',
    planName: 'Dinner Only',
    description: 'Evening meals with chapati and seasonal curry.',
    price: 2200,
    durationDays: 30,
    mealTypes: ['Dinner'],
    isActive: true,
  ),
  const Plan(
    planId: 'plan_004',
    messId: 'mess_002',
    planName: 'Lunch Only',
    description: 'Student-friendly lunch plan with unlimited roti.',
    price: 2200,
    durationDays: 30,
    mealTypes: ['Lunch'],
    isActive: true,
  ),
  const Plan(
    planId: 'plan_005',
    messId: 'mess_002',
    planName: 'Lunch + Dinner',
    description: 'Two meals per day with veg and non-veg options.',
    price: 3800,
    durationDays: 30,
    mealTypes: ['Lunch', 'Dinner'],
    isActive: true,
  ),
  const Plan(
    planId: 'plan_006',
    messId: 'mess_003',
    planName: 'Full Day',
    description: 'Three meals with North Indian thali style servings.',
    price: 4200,
    durationDays: 30,
    mealTypes: ['Breakfast', 'Lunch', 'Dinner'],
    isActive: true,
  ),
  const Plan(
    planId: 'plan_007',
    messId: 'mess_003',
    planName: 'Lunch Only',
    description: 'Daily thali with dessert on Sundays.',
    price: 2800,
    durationDays: 30,
    mealTypes: ['Lunch'],
    isActive: true,
  ),
  const Plan(
    planId: 'plan_008',
    messId: 'mess_004',
    planName: 'Dinner Only',
    description: 'Non-veg dinner with chicken or mutton rotation.',
    price: 3500,
    durationDays: 30,
    mealTypes: ['Dinner'],
    isActive: true,
  ),
  const Plan(
    planId: 'plan_009',
    messId: 'mess_004',
    planName: 'Lunch + Dinner',
    description: 'Premium non-veg meals with weekend biryani.',
    price: 5500,
    durationDays: 30,
    mealTypes: ['Lunch', 'Dinner'],
    isActive: true,
  ),
  const Plan(
    planId: 'plan_010',
    messId: 'mess_005',
    planName: 'Lunch Only',
    description: 'Pure veg lunch with jain-friendly options available.',
    price: 2400,
    durationDays: 30,
    mealTypes: ['Lunch'],
    isActive: true,
  ),
  const Plan(
    planId: 'plan_011',
    messId: 'mess_005',
    planName: 'Full Day',
    description: 'All three meals with organic produce focus.',
    price: 4000,
    durationDays: 30,
    mealTypes: ['Breakfast', 'Lunch', 'Dinner'],
    isActive: true,
  ),
];
