import '../../models/payment_item.dart';

final List<PaymentItem> fakePayments = [
  PaymentItem(
    paymentId: 'PMT001',
    transactionId: 'TXN839201948',
    amount: 2400.0,
    paymentDate: DateTime.now().subtract(const Duration(days: 2, hours: 3)),
    status: PaymentStatus.success,
    messName: 'Royal Deluxe Mess',
    planName: 'Monthly Unlimited Meal',
    paymentMethod: 'UPI (GPay)',
  ),
  PaymentItem(
    paymentId: 'PMT002',
    transactionId: 'TXN102938475',
    amount: 1500.0,
    paymentDate: DateTime.now().subtract(const Duration(days: 15, hours: 1)),
    status: PaymentStatus.success,
    messName: 'Moms Kitchen Mess',
    planName: '15 Meals Executive Plan',
    paymentMethod: 'UPI (PhonePe)',
  ),
  PaymentItem(
    paymentId: 'PMT003',
    transactionId: 'TXN562819203',
    amount: 3200.0,
    paymentDate: DateTime.now().subtract(const Duration(days: 30, hours: 5)),
    status: PaymentStatus.success,
    messName: 'Royal Deluxe Mess',
    planName: 'Monthly Premium Feast',
    paymentMethod: 'Credit Card',
  ),
  PaymentItem(
    paymentId: 'PMT004',
    transactionId: 'TXN990812344',
    amount: 1200.0,
    paymentDate: DateTime.now().subtract(const Duration(days: 31)),
    status: PaymentStatus.failed,
    messName: 'South Indian Aroma',
    planName: '10 Meals Trial Plan',
    paymentMethod: 'Net Banking',
  ),
  PaymentItem(
    paymentId: 'PMT005',
    transactionId: 'TXN483920112',
    amount: 2800.0,
    paymentDate: DateTime.now().subtract(const Duration(days: 45, hours: 4)),
    status: PaymentStatus.success,
    messName: 'Elite Greens Veg Mess',
    planName: 'Monthly Healthy Diet',
    paymentMethod: 'Debit Card',
  ),
  PaymentItem(
    paymentId: 'PMT006',
    transactionId: 'TXN112233445',
    amount: 2400.0,
    paymentDate: DateTime.now().subtract(const Duration(minutes: 45)),
    status: PaymentStatus.pending,
    messName: 'Royal Deluxe Mess',
    planName: 'Monthly Unlimited Meal',
    paymentMethod: 'UPI (Paytm)',
  ),
];
