import '../../models/subscription_model.dart';

final fakeSubscriptions = <Subscription>[
  Subscription(
    subscriptionId: 'sub_001',
    customerId: 'user_001',
    messId: 'mess_001',
    planId: 'plan_002',
    messName: 'Sai Mess',
    planName: 'Full Day',
    startDate: DateTime(2026, 5, 15),
    endDate: DateTime(2026, 6, 14),
    daysRemaining: 12,
    status: SubscriptionStatus.active,
  ),
  Subscription(
    subscriptionId: 'sub_002',
    customerId: 'user_001',
    messId: 'mess_002',
    planId: 'plan_005',
    messName: 'Annapurna Mess',
    planName: 'Lunch + Dinner',
    startDate: DateTime(2026, 5, 20),
    endDate: DateTime(2026, 6, 19),
    daysRemaining: 5,
    status: SubscriptionStatus.active,
  ),
  Subscription(
    subscriptionId: 'sub_003',
    customerId: 'user_001',
    messId: 'mess_004',
    planId: 'plan_008',
    messName: 'Royal Biryani Mess',
    planName: 'Dinner Only',
    startDate: DateTime(2026, 2, 1),
    endDate: DateTime(2026, 3, 2),
    daysRemaining: 0,
    status: SubscriptionStatus.expired,
  ),
  Subscription(
    subscriptionId: 'sub_004',
    customerId: 'user_001',
    messId: 'mess_003',
    planId: 'plan_007',
    messName: 'Shree Tiffin Centre',
    planName: 'Lunch Only',
    startDate: DateTime(2025, 11, 1),
    endDate: DateTime(2025, 12, 1),
    daysRemaining: 0,
    status: SubscriptionStatus.expired,
  ),
];
